### ISSUE TITLE
Script properties: 'depends-on' and 'creates'

### ISSUE THREAD

**Issue by NoF0rte** [analog-substance/arsenic#35]
```
as-dns-resolution:
  depends-on:
    - "recon/domains/*"
    - "scope-domains-generated-combined.txt"
  creates:
    - "recon/domains/*/resolv-domains.txt"
    - "scope-domains-generated-resolved.txt"
```

`depends-on` would be a list of files that the script requires in order to run
`creates` would be a list of files the script would create when run

This could possibly be used to determine order and we could check if the files exist before running a script
